language: ruby
cache: bundler

sudo: false

install:
  - true

script:
  - true
  
secure: "hBatM+0xuGTYvwYctS2z/aCQLyQPLQ71rJOU7+d939m3DZywS2gt2SUhxEQfGp+DL0v+Mgp7d1vmyrV/sbhqDsSlbTq3C+Lm2hbwDVQr4wUV/fzC3e+67ZqrnVlJ2ReCiratSat/Dle3q2xxsnxMHa851J+N4VUWOn/Gfp5tjbs="

notifications:
  email: false
